export interface WordProps {
  A: Word[]
  B: Word[]
  C: Word[]
  D: Word[]
  E: Word[]
  F: Word[]
  G: Word[]
  H: Word[]
  I: Word[]
  J: Word[]
  K: Word[]
  L: Word[]
  M: Word[]
  N: Word[]
  O: Word[]
  P: Word[]
  Q: Word[]
  R: Word[]
  S: Word[]
  T: Word[]
  U: Word[]
  V: Word[]
  W: Word[]
  X: Word[]
  Y: Word[]
  Z: Word[]
}

export interface Word {
  mean: string
  word: string
}
